### ISSUE TITLE
Upgrade with spdx-expression-parse 3.0.0?

### ISSUE THREAD

**Issue by jinwoo** [jslicense/spdx-satisfies.js#2]
Now that `spdx-correct` and `spdx-expression-parse` have been upgraded to 3.0.0, can you please also publish `spdx-satisfies` to use `spdx-expression-parse` 3.0.0?

Otherwise, when passing some license names corrected by `spdx-correct` 3.0.0 to `spdx-satisfies()`, it throws an error (Unrecognized text).

**Comment by kemitchell** [comment]
Might you send a pull request?

**Comment by jinwoo** [comment]
Sure. I'll try to come up with a PR soon.

**Comment by jinwoo** [comment]
Just created https://github.com/jslicense/spdx-satisfies.js/pull/3. Please take a look!

**Comment by jinwoo** [comment]
@kemitchell Can you also publish a new NPM with this change? Is it blocked by https://github.com/jslicense/spdx-satisfies.js/issues/4?
